FormatVersion: OOS-2019-06-01
Description:
  en: Modify audit log config
  zh-cn: 开启redis审计日志，保留时长180天
  name-en: ACS-REDIS-BulkyModifyAuditLogConfig
  name-zh-cn: 开启redis审计日志，保留时长180天
  categories:
    - security
Parameters:
  regionId:
    Type: String
    Label:
      en: RegionId
      zh-cn: 地域ID
    AssociationProperty: RegionId
    Default: '{{ ACS::RegionId }}'
  instanceId:
    Label:
      en: RedisInstanceIds
      zh-cn: Redis实例ID列表
    Type: List
  rateControl:
    Label:
      en: RateControl
      zh-cn: 任务执行的并发比率
    Type: Json
    AssociationProperty: RateControl
    Default:
      Mode: Concurrency
      MaxErrors: 0
      Concurrency: 10
  OOSAssumeRole:
    Label:
      en: OOSAssumeRole
      zh-cn: OOS扮演的RAM角色
    Type: String
    Default: ''
RamRole: '{{ OOSAssumeRole }}'
Tasks:
  - Name: modifyAuditLogConfig
    Action: 'ACS::ExecuteAPI'
    Description:
      en: Modify audit log config
      zh-cn: 开启redis审计日志，保留时长180天
    Properties:
      Service: R-KVSTORE
      API: ModifyAuditLogConfig
      Parameters:
        RegionId: '{{ regionId }}'
        InstanceId: '{{ ACS::TaskLoopItem }}'
        DbAudit: true
        Retention: 180
    Loop:
      RateControl: '{{ rateControl }}'
      Items: '{{ instanceId }}'
